### PR TITLE
[models] Improve error message format #44

### LINKED ISSUE #44: [models] Improve error message when validating PEM format
**Reserved for GCI**

When importing a certificate or CA, a mistake in the PEM formatted fields will trigger a validation error, which will report internal pyopenssl messages which are not easy to understand.

### PR DESCRIPTION
**Pull request by dwang**
Messages will be more human readable.
The square brackets are removed and line breaks are added.

Fixes #44

### CODE REVIEW

**Comment by R9295** [comment]
@dwang hey, some tests are failing, please fix them too. run ```./runtests.py``` before pushing always to see if your changes break any tests. In this case the tests are still expecting the old format of the error. Adjust them to the new error messages.

**Comment by dwang** [comment]
Sorry about that!

The tests pass now. I have amended the commit with the fixes.

**Comment by R9295** [comment]
@dwang Nice! @nemesisdesign looks good to me, I'll leave the final bit to you.

**Comment by dwang** [comment]
Sorry, I messed up a parenthesis when making the line shorter.
It should be fixed now.

screen shot 2018-10-24 at 3 35 30 pm

**Comment by nemesisdesign** [comment]
@dwang remember to send your task for review so we can approve it

**Pull request merged**
