### PR TITLE
[WIP] Support Python 3.8 / Django 3

### PR DESCRIPTION
**Pull request by takkaria**

### CODE REVIEW

**Comment by takkaria** [comment]
I was hoping that  it would be straightforward to upgrade to Django 3, but apparently not.  I'll fix the issues and add the commits to the PR.

**Comment by takkaria** [comment]
So it looks like to support Django 3.0 we'd need to drop Python 2.7 support.  That's because this package depends on `django-model-utils` which at the same time as being updated to support Django 3 is having Python 2 compatibility removed.  Are you happy with that @nemesisdesign ?  If so I will amend this PR when a new version of `django-model-utils` is released.

**Comment by atb00ker** [comment]
The title of the PR looks awesome, thanks @takkaria 

About Python2.7 support, we indent to drop it, so I suppose this sounds about right! :smile:

**Comment by takkaria** [comment]
Closing as it looks like #70 is handling this pretty well.

**Comment by nemesisdesign** [comment]
@takkaria Thanks for contributing and closing the PR :+1: :+1:

**Pull request closed without merging**
