### PR TITLE
[fix] Fixed render issue in popup page #113

### LINKED ISSUE #113: [bug] Render Issue in popup page
It's related to the Issue mentioned here https://github.com/openwisp/openwisp-controller/issues/375. 
It should be solved from here.

**How to reproduce**
1. Go to change page of ca.
2. add ``?_to_field=id&_popup=1`` in the url and refresh the page.

### PR DESCRIPTION
**Pull request by niteshsinha17**
@nemesisdesign Before writing tests I wanted to show the implementation. Is it ok? I will need to use selenium in the test.

closes #113

### CODE REVIEW

**Review by atb00ker — APPROVED** [review]
Tested, works, solution looks good, not sure if we want to start with Integration testing here...

**Review by atb00ker — CHANGES_REQUESTED** [review]
Wait, noticed a problem, when I try to create a new CA from from certificate's add form, I don't get the option to select if I want create new or import.
This change should only affect the change page! :smile:

**Review by nemesisdesign — CHANGES_REQUESTED** [review]
> Wait, noticed a problem, when I try to create a new CA from from certificate's add form, I don't get the option to select if I want create new or import.
> This change should only affect the change page! smile

Definitely.

@niteshsinha17 please spend time testing that your changes do not affect negatively the existing features.

**Comment by niteshsinha17** [comment]
> Wait, noticed a problem, when I try to create a new CA from from certificate's add form, I don't get the option to select if I want create new or import.
> This change should only affect the change page! 😄

@atb00ker Thanks for spotting this. I have fixed it. Please check.

**Review by nemesisdesign — APPROVED** [review]
Thanks @niteshsinha17 and @atb00ker for your precious review & testing :+1:

**Pull request merged**
